# Generated by Django 4.1.5 on 2023-01-19 17:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lastName', models.TextField()),
                ('firstName', models.TextField()),
                ('companyName', models.TextField()),
                ('password', models.TextField()),
                ('email', models.TextField()),
                ('phone', models.TextField()),
                ('city', models.TextField()),
                ('kvk', models.TextField()),
                ('jobCategory', models.TextField()),
                ('userType', models.TextField()),
                ('premium', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Post',
        ),
    ]
